var searchData=
[
  ['iboundingbox_0',['IBoundingBox',['../da/d5e/classCE_1_1IBoundingBox.html',1,'CE']]],
  ['icomponentes_1',['IComponentes',['../d8/d82/classCE_1_1IComponentes.html',1,'CE']]],
  ['icontrol_2',['IControl',['../de/d09/classCE_1_1IControl.html',1,'CE']]],
  ['idialogo_3',['IDialogo',['../d9/db3/classIVJ_1_1IDialogo.html',1,'IVJ']]],
  ['iindicador_4',['IIndicador',['../d0/dd9/classIVJ_1_1IIndicador.html',1,'IVJ']]],
  ['iinteractuable_5',['IInteractuable',['../db/dd6/classIVJ_1_1IInteractuable.html',1,'IVJ']]],
  ['iiterador_6',['IIterador',['../d4/dda/classCE_1_1IIterador.html',1,'CE']]],
  ['iiterador_3c_20std_3a_3apair_3c_20std_3a_3astring_2c_20niveles_20_3e_20_3e_7',['IIterador&lt; std::pair&lt; std::string, Niveles &gt; &gt;',['../d4/dda/classCE_1_1IIterador.html',1,'CE']]],
  ['imanipulardatos_8',['IManipularDatos',['../d9/d04/classCE_1_1IManipularDatos.html',1,'CE']]],
  ['imanipulardatos_3c_20std_3a_3apair_3c_20std_3a_3astring_2c_20niveles_20_3e_20_3e_9',['IManipularDatos&lt; std::pair&lt; std::string, Niveles &gt; &gt;',['../d9/d04/classCE_1_1IManipularDatos.html',1,'CE']]],
  ['imaquinaestado_10',['IMaquinaEstado',['../d3/d79/classIVJ_1_1IMaquinaEstado.html',1,'IVJ']]],
  ['imbitarray_11',['ImBitArray',['../d5/d97/structImBitArray.html',1,'']]],
  ['imbitarray_3c_20imguikey_5fnamedkey_5fcount_2c_20_2dimguikey_5fnamedkey_5fbegin_20_3e_12',['ImBitArray&lt; ImGuiKey_NamedKey_COUNT, -ImGuiKey_NamedKey_BEGIN &gt;',['../d5/d97/structImBitArray.html',1,'']]],
  ['imbitvector_13',['ImBitVector',['../d4/d9b/structImBitVector.html',1,'']]],
  ['imchunkstream_14',['ImChunkStream',['../d0/d22/structImChunkStream.html',1,'']]],
  ['imchunkstream_3c_20imguitablesettings_20_3e_15',['ImChunkStream&lt; ImGuiTableSettings &gt;',['../d0/d22/structImChunkStream.html',1,'']]],
  ['imchunkstream_3c_20imguiwindowsettings_20_3e_16',['ImChunkStream&lt; ImGuiWindowSettings &gt;',['../d0/d22/structImChunkStream.html',1,'']]],
  ['imcolor_17',['ImColor',['../dc/d86/structImColor.html',1,'']]],
  ['imdrawchannel_18',['ImDrawChannel',['../d7/d3a/structImDrawChannel.html',1,'']]],
  ['imdrawcmd_19',['ImDrawCmd',['../d9/de6/structImDrawCmd.html',1,'']]],
  ['imdrawcmdheader_20',['ImDrawCmdHeader',['../d3/d79/structImDrawCmdHeader.html',1,'']]],
  ['imdrawdata_21',['ImDrawData',['../d9/d41/structImDrawData.html',1,'']]],
  ['imdrawdatabuilder_22',['ImDrawDataBuilder',['../dd/dff/structImDrawDataBuilder.html',1,'']]],
  ['imdrawlist_23',['ImDrawList',['../d2/d31/structImDrawList.html',1,'']]],
  ['imdrawlistshareddata_24',['ImDrawListSharedData',['../d2/d89/structImDrawListSharedData.html',1,'']]],
  ['imdrawlistsplitter_25',['ImDrawListSplitter',['../d5/dfd/structImDrawListSplitter.html',1,'']]],
  ['imdrawvert_26',['ImDrawVert',['../d3/dfa/structImDrawVert.html',1,'']]],
  ['imdrawvertallegro_27',['ImDrawVertAllegro',['../d4/d51/structImDrawVertAllegro.html',1,'']]],
  ['imfont_28',['ImFont',['../dd/d61/structImFont.html',1,'']]],
  ['imfontatlas_29',['ImFontAtlas',['../dc/d21/structImFontAtlas.html',1,'']]],
  ['imfontatlascustomrect_30',['ImFontAtlasCustomRect',['../d8/d8f/structImFontAtlasCustomRect.html',1,'']]],
  ['imfontbuilddstdata_31',['ImFontBuildDstData',['../d7/d51/structImFontBuildDstData.html',1,'']]],
  ['imfontbuilddstdataft_32',['ImFontBuildDstDataFT',['../dc/d11/structImFontBuildDstDataFT.html',1,'']]],
  ['imfontbuilderio_33',['ImFontBuilderIO',['../d8/d39/structImFontBuilderIO.html',1,'']]],
  ['imfontbuildsrcdata_34',['ImFontBuildSrcData',['../dd/d86/structImFontBuildSrcData.html',1,'']]],
  ['imfontbuildsrcdataft_35',['ImFontBuildSrcDataFT',['../d2/dc8/structImFontBuildSrcDataFT.html',1,'']]],
  ['imfontbuildsrcglyphft_36',['ImFontBuildSrcGlyphFT',['../df/d30/structImFontBuildSrcGlyphFT.html',1,'']]],
  ['imfontconfig_37',['ImFontConfig',['../df/d67/structImFontConfig.html',1,'']]],
  ['imfontglyph_38',['ImFontGlyph',['../d3/db9/structImFontGlyph.html',1,'']]],
  ['imfontglyphrangesbuilder_39',['ImFontGlyphRangesBuilder',['../db/d52/structImFontGlyphRangesBuilder.html',1,'']]],
  ['imgl3wprocs_40',['ImGL3WProcs',['../d8/db6/unionImGL3WProcs.html',1,'']]],
  ['imgui_5fimplallegro5_5fdata_41',['ImGui_ImplAllegro5_Data',['../d2/d91/structImGui__ImplAllegro5__Data.html',1,'']]],
  ['imgui_5fimpldx10_5fdata_42',['ImGui_ImplDX10_Data',['../d2/d91/structImGui__ImplDX10__Data.html',1,'']]],
  ['imgui_5fimpldx10_5frenderstate_43',['ImGui_ImplDX10_RenderState',['../d5/d49/structImGui__ImplDX10__RenderState.html',1,'']]],
  ['imgui_5fimpldx10_5fviewportdata_44',['ImGui_ImplDX10_ViewportData',['../d6/d2a/structImGui__ImplDX10__ViewportData.html',1,'']]],
  ['imgui_5fimpldx11_5fdata_45',['ImGui_ImplDX11_Data',['../db/d1f/structImGui__ImplDX11__Data.html',1,'']]],
  ['imgui_5fimpldx11_5frenderstate_46',['ImGui_ImplDX11_RenderState',['../d9/d98/structImGui__ImplDX11__RenderState.html',1,'']]],
  ['imgui_5fimpldx11_5fviewportdata_47',['ImGui_ImplDX11_ViewportData',['../db/daf/structImGui__ImplDX11__ViewportData.html',1,'']]],
  ['imgui_5fimpldx12_5fdata_48',['ImGui_ImplDX12_Data',['../d4/d75/structImGui__ImplDX12__Data.html',1,'']]],
  ['imgui_5fimpldx12_5fframecontext_49',['ImGui_ImplDX12_FrameContext',['../d3/da4/structImGui__ImplDX12__FrameContext.html',1,'']]],
  ['imgui_5fimpldx12_5finitinfo_50',['ImGui_ImplDX12_InitInfo',['../d1/d06/structImGui__ImplDX12__InitInfo.html',1,'']]],
  ['imgui_5fimpldx12_5frenderbuffers_51',['ImGui_ImplDX12_RenderBuffers',['../d5/dfb/structImGui__ImplDX12__RenderBuffers.html',1,'']]],
  ['imgui_5fimpldx12_5frenderstate_52',['ImGui_ImplDX12_RenderState',['../d8/dd5/structImGui__ImplDX12__RenderState.html',1,'']]],
  ['imgui_5fimpldx12_5ftexture_53',['ImGui_ImplDX12_Texture',['../d0/dbb/structImGui__ImplDX12__Texture.html',1,'']]],
  ['imgui_5fimpldx12_5fviewportdata_54',['ImGui_ImplDX12_ViewportData',['../da/dce/structImGui__ImplDX12__ViewportData.html',1,'']]],
  ['imgui_5fimpldx9_5fdata_55',['ImGui_ImplDX9_Data',['../da/dc9/structImGui__ImplDX9__Data.html',1,'']]],
  ['imgui_5fimpldx9_5fviewportdata_56',['ImGui_ImplDX9_ViewportData',['../d5/def/structImGui__ImplDX9__ViewportData.html',1,'']]],
  ['imgui_5fimplglfw_5fdata_57',['ImGui_ImplGlfw_Data',['../d1/d89/structImGui__ImplGlfw__Data.html',1,'']]],
  ['imgui_5fimplglfw_5fviewportdata_58',['ImGui_ImplGlfw_ViewportData',['../d0/d7b/structImGui__ImplGlfw__ViewportData.html',1,'']]],
  ['imgui_5fimplmetal_5fdata_59',['ImGui_ImplMetal_Data',['../d7/dda/structImGui__ImplMetal__Data.html',1,'']]],
  ['imgui_5fimplopengl2_5fdata_60',['ImGui_ImplOpenGL2_Data',['../da/d32/structImGui__ImplOpenGL2__Data.html',1,'']]],
  ['imgui_5fimplopengl3_5fdata_61',['ImGui_ImplOpenGL3_Data',['../d4/d46/structImGui__ImplOpenGL3__Data.html',1,'']]],
  ['imgui_5fimplosx_5fdata_62',['ImGui_ImplOSX_Data',['../d5/d43/structImGui__ImplOSX__Data.html',1,'']]],
  ['imgui_5fimplosx_5fwindow_63',['ImGui_ImplOSX_Window',['../d0/d92/interfaceImGui__ImplOSX__Window.html',1,'']]],
  ['imgui_5fimplsdl2_5fdata_64',['ImGui_ImplSDL2_Data',['../d4/d75/structImGui__ImplSDL2__Data.html',1,'']]],
  ['imgui_5fimplsdl2_5fviewportdata_65',['ImGui_ImplSDL2_ViewportData',['../d9/d69/structImGui__ImplSDL2__ViewportData.html',1,'']]],
  ['imgui_5fimplsdl3_5fdata_66',['ImGui_ImplSDL3_Data',['../d2/d15/structImGui__ImplSDL3__Data.html',1,'']]],
  ['imgui_5fimplsdl3_5fviewportdata_67',['ImGui_ImplSDL3_ViewportData',['../d2/d8f/structImGui__ImplSDL3__ViewportData.html',1,'']]],
  ['imgui_5fimplsdlgpu3_5fdata_68',['ImGui_ImplSDLGPU3_Data',['../d7/dbb/structImGui__ImplSDLGPU3__Data.html',1,'']]],
  ['imgui_5fimplsdlgpu3_5fframedata_69',['ImGui_ImplSDLGPU3_FrameData',['../d3/d88/structImGui__ImplSDLGPU3__FrameData.html',1,'']]],
  ['imgui_5fimplsdlgpu3_5finitinfo_70',['ImGui_ImplSDLGPU3_InitInfo',['../d4/df5/structImGui__ImplSDLGPU3__InitInfo.html',1,'']]],
  ['imgui_5fimplsdlrenderer2_5fdata_71',['ImGui_ImplSDLRenderer2_Data',['../d4/d69/structImGui__ImplSDLRenderer2__Data.html',1,'']]],
  ['imgui_5fimplsdlrenderer2_5frenderstate_72',['ImGui_ImplSDLRenderer2_RenderState',['../d3/ddf/structImGui__ImplSDLRenderer2__RenderState.html',1,'']]],
  ['imgui_5fimplsdlrenderer3_5fdata_73',['ImGui_ImplSDLRenderer3_Data',['../d8/d85/structImGui__ImplSDLRenderer3__Data.html',1,'']]],
  ['imgui_5fimplsdlrenderer3_5frenderstate_74',['ImGui_ImplSDLRenderer3_RenderState',['../d0/d9d/structImGui__ImplSDLRenderer3__RenderState.html',1,'']]],
  ['imgui_5fimplvulkan_5fdata_75',['ImGui_ImplVulkan_Data',['../de/dfc/structImGui__ImplVulkan__Data.html',1,'']]],
  ['imgui_5fimplvulkan_5fframerenderbuffers_76',['ImGui_ImplVulkan_FrameRenderBuffers',['../d1/d4f/structImGui__ImplVulkan__FrameRenderBuffers.html',1,'']]],
  ['imgui_5fimplvulkan_5finitinfo_77',['ImGui_ImplVulkan_InitInfo',['../d2/dbb/structImGui__ImplVulkan__InitInfo.html',1,'']]],
  ['imgui_5fimplvulkan_5frenderstate_78',['ImGui_ImplVulkan_RenderState',['../d5/da1/structImGui__ImplVulkan__RenderState.html',1,'']]],
  ['imgui_5fimplvulkan_5ftexture_79',['ImGui_ImplVulkan_Texture',['../d4/de1/structImGui__ImplVulkan__Texture.html',1,'']]],
  ['imgui_5fimplvulkan_5fviewportdata_80',['ImGui_ImplVulkan_ViewportData',['../d6/dd1/structImGui__ImplVulkan__ViewportData.html',1,'']]],
  ['imgui_5fimplvulkan_5fwindowrenderbuffers_81',['ImGui_ImplVulkan_WindowRenderBuffers',['../d3/d97/structImGui__ImplVulkan__WindowRenderBuffers.html',1,'']]],
  ['imgui_5fimplvulkanh_5fframe_82',['ImGui_ImplVulkanH_Frame',['../dd/d41/structImGui__ImplVulkanH__Frame.html',1,'']]],
  ['imgui_5fimplvulkanh_5fframesemaphores_83',['ImGui_ImplVulkanH_FrameSemaphores',['../dd/ddd/structImGui__ImplVulkanH__FrameSemaphores.html',1,'']]],
  ['imgui_5fimplvulkanh_5fwindow_84',['ImGui_ImplVulkanH_Window',['../d5/d7a/structImGui__ImplVulkanH__Window.html',1,'']]],
  ['imgui_5fimplwgpu_5fdata_85',['ImGui_ImplWGPU_Data',['../d9/d80/structImGui__ImplWGPU__Data.html',1,'']]],
  ['imgui_5fimplwgpu_5finitinfo_86',['ImGui_ImplWGPU_InitInfo',['../d8/daf/structImGui__ImplWGPU__InitInfo.html',1,'']]],
  ['imgui_5fimplwgpu_5frenderstate_87',['ImGui_ImplWGPU_RenderState',['../da/d60/structImGui__ImplWGPU__RenderState.html',1,'']]],
  ['imgui_5fimplwin32_5fdata_88',['ImGui_ImplWin32_Data',['../d6/d89/structImGui__ImplWin32__Data.html',1,'']]],
  ['imgui_5fimplwin32_5fviewportdata_89',['ImGui_ImplWin32_ViewportData',['../de/db9/structImGui__ImplWin32__ViewportData.html',1,'']]],
  ['imguiboxselectstate_90',['ImGuiBoxSelectState',['../db/d1f/structImGuiBoxSelectState.html',1,'']]],
  ['imguicolormod_91',['ImGuiColorMod',['../d5/d92/structImGuiColorMod.html',1,'']]],
  ['imguicombopreviewdata_92',['ImGuiComboPreviewData',['../db/d4e/structImGuiComboPreviewData.html',1,'']]],
  ['imguicontext_93',['ImGuiContext',['../d3/df1/structImGuiContext.html',1,'']]],
  ['imguicontexthook_94',['ImGuiContextHook',['../da/d0e/structImGuiContextHook.html',1,'']]],
  ['imguidatatypeinfo_95',['ImGuiDataTypeInfo',['../d6/d25/structImGuiDataTypeInfo.html',1,'']]],
  ['imguidatatypestorage_96',['ImGuiDataTypeStorage',['../d7/d03/structImGuiDataTypeStorage.html',1,'']]],
  ['imguideactivateditemdata_97',['ImGuiDeactivatedItemData',['../d9/df6/structImGuiDeactivatedItemData.html',1,'']]],
  ['imguidebugallocentry_98',['ImGuiDebugAllocEntry',['../d3/d2d/structImGuiDebugAllocEntry.html',1,'']]],
  ['imguidebugallocinfo_99',['ImGuiDebugAllocInfo',['../d8/df4/structImGuiDebugAllocInfo.html',1,'']]],
  ['imguidemowindowdata_100',['ImGuiDemoWindowData',['../d4/d4a/structImGuiDemoWindowData.html',1,'']]],
  ['imguidockcontext_101',['ImGuiDockContext',['../d4/def/structImGuiDockContext.html',1,'']]],
  ['imguidockcontextprunenodedata_102',['ImGuiDockContextPruneNodeData',['../de/d67/structImGuiDockContextPruneNodeData.html',1,'']]],
  ['imguidocknode_103',['ImGuiDockNode',['../d6/df3/structImGuiDockNode.html',1,'']]],
  ['imguidocknodesettings_104',['ImGuiDockNodeSettings',['../df/df4/structImGuiDockNodeSettings.html',1,'']]],
  ['imguidocknodetreeinfo_105',['ImGuiDockNodeTreeInfo',['../dc/d80/structImGuiDockNodeTreeInfo.html',1,'']]],
  ['imguidockpreviewdata_106',['ImGuiDockPreviewData',['../db/d25/structImGuiDockPreviewData.html',1,'']]],
  ['imguidockrequest_107',['ImGuiDockRequest',['../d6/db3/structImGuiDockRequest.html',1,'']]],
  ['imguierrorrecoverystate_108',['ImGuiErrorRecoveryState',['../d7/dda/structImGuiErrorRecoveryState.html',1,'']]],
  ['imguifocusscopedata_109',['ImGuiFocusScopeData',['../db/dda/structImGuiFocusScopeData.html',1,'']]],
  ['imguigetnamefromindexoldtonewcallbackdata_110',['ImGuiGetNameFromIndexOldToNewCallbackData',['../da/d80/structImGuiGetNameFromIndexOldToNewCallbackData.html',1,'']]],
  ['imguigroupdata_111',['ImGuiGroupData',['../d0/dea/structImGuiGroupData.html',1,'']]],
  ['imguiidstacktool_112',['ImGuiIDStackTool',['../d7/d96/structImGuiIDStackTool.html',1,'']]],
  ['imguiinputevent_113',['ImGuiInputEvent',['../d5/db6/structImGuiInputEvent.html',1,'']]],
  ['imguiinputeventappfocused_114',['ImGuiInputEventAppFocused',['../d1/d86/structImGuiInputEventAppFocused.html',1,'']]],
  ['imguiinputeventkey_115',['ImGuiInputEventKey',['../da/df4/structImGuiInputEventKey.html',1,'']]],
  ['imguiinputeventmousebutton_116',['ImGuiInputEventMouseButton',['../d6/d5a/structImGuiInputEventMouseButton.html',1,'']]],
  ['imguiinputeventmousepos_117',['ImGuiInputEventMousePos',['../db/d1e/structImGuiInputEventMousePos.html',1,'']]],
  ['imguiinputeventmouseviewport_118',['ImGuiInputEventMouseViewport',['../dc/df8/structImGuiInputEventMouseViewport.html',1,'']]],
  ['imguiinputeventmousewheel_119',['ImGuiInputEventMouseWheel',['../d1/d66/structImGuiInputEventMouseWheel.html',1,'']]],
  ['imguiinputeventtext_120',['ImGuiInputEventText',['../d8/db2/structImGuiInputEventText.html',1,'']]],
  ['imguiinputtextcallbackdata_121',['ImGuiInputTextCallbackData',['../db/d94/structImGuiInputTextCallbackData.html',1,'']]],
  ['imguiinputtextdeactivatedstate_122',['ImGuiInputTextDeactivatedState',['../d1/d57/structImGuiInputTextDeactivatedState.html',1,'']]],
  ['imguiinputtextstate_123',['ImGuiInputTextState',['../d0/d3f/structImGuiInputTextState.html',1,'']]],
  ['imguiio_124',['ImGuiIO',['../df/d8f/structImGuiIO.html',1,'']]],
  ['imguikeydata_125',['ImGuiKeyData',['../d5/dcf/structImGuiKeyData.html',1,'']]],
  ['imguikeyownerdata_126',['ImGuiKeyOwnerData',['../d7/d5f/structImGuiKeyOwnerData.html',1,'']]],
  ['imguikeyroutingdata_127',['ImGuiKeyRoutingData',['../d5/d36/structImGuiKeyRoutingData.html',1,'']]],
  ['imguikeyroutingtable_128',['ImGuiKeyRoutingTable',['../d0/d2e/structImGuiKeyRoutingTable.html',1,'']]],
  ['imguilastitemdata_129',['ImGuiLastItemData',['../d9/d87/structImGuiLastItemData.html',1,'']]],
  ['imguilistclipper_130',['ImGuiListClipper',['../d3/d32/structImGuiListClipper.html',1,'']]],
  ['imguilistclipperdata_131',['ImGuiListClipperData',['../d3/d87/structImGuiListClipperData.html',1,'']]],
  ['imguilistclipperrange_132',['ImGuiListClipperRange',['../da/dde/structImGuiListClipperRange.html',1,'']]],
  ['imguilocentry_133',['ImGuiLocEntry',['../d3/d0a/structImGuiLocEntry.html',1,'']]],
  ['imguimenucolumns_134',['ImGuiMenuColumns',['../d4/d27/structImGuiMenuColumns.html',1,'']]],
  ['imguimetricsconfig_135',['ImGuiMetricsConfig',['../df/d37/structImGuiMetricsConfig.html',1,'']]],
  ['imguimultiselectio_136',['ImGuiMultiSelectIO',['../da/dcb/structImGuiMultiSelectIO.html',1,'']]],
  ['imguimultiselectstate_137',['ImGuiMultiSelectState',['../d0/de8/structImGuiMultiSelectState.html',1,'']]],
  ['imguimultiselecttempdata_138',['ImGuiMultiSelectTempData',['../d5/d97/structImGuiMultiSelectTempData.html',1,'']]],
  ['imguinavitemdata_139',['ImGuiNavItemData',['../d5/d66/structImGuiNavItemData.html',1,'']]],
  ['imguinextitemdata_140',['ImGuiNextItemData',['../d7/d91/structImGuiNextItemData.html',1,'']]],
  ['imguinextwindowdata_141',['ImGuiNextWindowData',['../d4/d21/structImGuiNextWindowData.html',1,'']]],
  ['imguiobserver_142',['ImGuiObserver',['../d8/da4/interfaceImGuiObserver.html',1,'']]],
  ['imguioldcolumndata_143',['ImGuiOldColumnData',['../da/d28/structImGuiOldColumnData.html',1,'']]],
  ['imguioldcolumns_144',['ImGuiOldColumns',['../d6/dc1/structImGuiOldColumns.html',1,'']]],
  ['imguionceuponaframe_145',['ImGuiOnceUponAFrame',['../d3/d41/structImGuiOnceUponAFrame.html',1,'']]],
  ['imguipayload_146',['ImGuiPayload',['../d7/daa/structImGuiPayload.html',1,'']]],
  ['imguiplatformimedata_147',['ImGuiPlatformImeData',['../d0/df9/structImGuiPlatformImeData.html',1,'']]],
  ['imguiplatformio_148',['ImGuiPlatformIO',['../d5/de2/structImGuiPlatformIO.html',1,'']]],
  ['imguiplatformmonitor_149',['ImGuiPlatformMonitor',['../da/ddb/structImGuiPlatformMonitor.html',1,'']]],
  ['imguiplotarraygetterdata_150',['ImGuiPlotArrayGetterData',['../d2/d67/structImGuiPlotArrayGetterData.html',1,'']]],
  ['imguipopupdata_151',['ImGuiPopupData',['../d2/d01/structImGuiPopupData.html',1,'']]],
  ['imguiptrorindex_152',['ImGuiPtrOrIndex',['../da/d87/structImGuiPtrOrIndex.html',1,'']]],
  ['imguiresizeborderdef_153',['ImGuiResizeBorderDef',['../d2/d4a/structImGuiResizeBorderDef.html',1,'']]],
  ['imguiresizegripdef_154',['ImGuiResizeGripDef',['../d3/df1/structImGuiResizeGripDef.html',1,'']]],
  ['imguiselectionbasicstorage_155',['ImGuiSelectionBasicStorage',['../d1/d07/structImGuiSelectionBasicStorage.html',1,'']]],
  ['imguiselectionexternalstorage_156',['ImGuiSelectionExternalStorage',['../dc/d42/structImGuiSelectionExternalStorage.html',1,'']]],
  ['imguiselectionrequest_157',['ImGuiSelectionRequest',['../d3/ddc/structImGuiSelectionRequest.html',1,'']]],
  ['imguisettingshandler_158',['ImGuiSettingsHandler',['../d5/d13/structImGuiSettingsHandler.html',1,'']]],
  ['imguishrinkwidthitem_159',['ImGuiShrinkWidthItem',['../dd/d61/structImGuiShrinkWidthItem.html',1,'']]],
  ['imguisizecallbackdata_160',['ImGuiSizeCallbackData',['../d0/d9c/structImGuiSizeCallbackData.html',1,'']]],
  ['imguistacklevelinfo_161',['ImGuiStackLevelInfo',['../d2/da7/structImGuiStackLevelInfo.html',1,'']]],
  ['imguistorage_162',['ImGuiStorage',['../d5/d44/structImGuiStorage.html',1,'']]],
  ['imguistoragepair_163',['ImGuiStoragePair',['../db/d36/structImGuiStoragePair.html',1,'']]],
  ['imguistyle_164',['ImGuiStyle',['../d8/d89/structImGuiStyle.html',1,'']]],
  ['imguistylemod_165',['ImGuiStyleMod',['../d3/dbe/structImGuiStyleMod.html',1,'']]],
  ['imguistylevarinfo_166',['ImGuiStyleVarInfo',['../d3/d4f/structImGuiStyleVarInfo.html',1,'']]],
  ['imguitabbar_167',['ImGuiTabBar',['../dd/df2/structImGuiTabBar.html',1,'']]],
  ['imguitabbarsection_168',['ImGuiTabBarSection',['../dd/d1e/structImGuiTabBarSection.html',1,'']]],
  ['imguitabitem_169',['ImGuiTabItem',['../d9/d99/structImGuiTabItem.html',1,'']]],
  ['imguitable_170',['ImGuiTable',['../de/d8f/structImGuiTable.html',1,'']]],
  ['imguitablecelldata_171',['ImGuiTableCellData',['../db/d70/structImGuiTableCellData.html',1,'']]],
  ['imguitablecolumn_172',['ImGuiTableColumn',['../d6/d19/structImGuiTableColumn.html',1,'']]],
  ['imguitablecolumnsettings_173',['ImGuiTableColumnSettings',['../d2/d08/structImGuiTableColumnSettings.html',1,'']]],
  ['imguitablecolumnsortspecs_174',['ImGuiTableColumnSortSpecs',['../db/db2/structImGuiTableColumnSortSpecs.html',1,'']]],
  ['imguitableheaderdata_175',['ImGuiTableHeaderData',['../d1/d06/structImGuiTableHeaderData.html',1,'']]],
  ['imguitableinstancedata_176',['ImGuiTableInstanceData',['../d8/ddd/structImGuiTableInstanceData.html',1,'']]],
  ['imguitablesettings_177',['ImGuiTableSettings',['../dc/d18/structImGuiTableSettings.html',1,'']]],
  ['imguitablesortspecs_178',['ImGuiTableSortSpecs',['../d0/ddc/structImGuiTableSortSpecs.html',1,'']]],
  ['imguitabletempdata_179',['ImGuiTableTempData',['../d9/d14/structImGuiTableTempData.html',1,'']]],
  ['imguitextbuffer_180',['ImGuiTextBuffer',['../d2/d1d/structImGuiTextBuffer.html',1,'']]],
  ['imguitextfilter_181',['ImGuiTextFilter',['../da/de6/structImGuiTextFilter.html',1,'']]],
  ['imguitextindex_182',['ImGuiTextIndex',['../d2/d65/structImGuiTextIndex.html',1,'']]],
  ['imguitextrange_183',['ImGuiTextRange',['../d7/db6/structImGuiTextFilter_1_1ImGuiTextRange.html',1,'ImGuiTextFilter']]],
  ['imguitreenodestackdata_184',['ImGuiTreeNodeStackData',['../d5/ded/structImGuiTreeNodeStackData.html',1,'']]],
  ['imguitypingselectrequest_185',['ImGuiTypingSelectRequest',['../d3/deb/structImGuiTypingSelectRequest.html',1,'']]],
  ['imguitypingselectstate_186',['ImGuiTypingSelectState',['../d1/dc0/structImGuiTypingSelectState.html',1,'']]],
  ['imguiviewport_187',['ImGuiViewport',['../d9/d9a/structImGuiViewport.html',1,'']]],
  ['imguiviewportdatametal_188',['ImGuiViewportDataMetal',['../da/dbb/structImGuiViewportDataMetal.html',1,'']]],
  ['imguiviewportdataosx_189',['ImGuiViewportDataOSX',['../da/dcb/structImGuiViewportDataOSX.html',1,'']]],
  ['imguiviewportp_190',['ImGuiViewportP',['../d3/d20/structImGuiViewportP.html',1,'']]],
  ['imguiwindow_191',['ImGuiWindow',['../df/d95/structImGuiWindow.html',1,'']]],
  ['imguiwindowclass_192',['ImGuiWindowClass',['../dc/d47/structImGuiWindowClass.html',1,'']]],
  ['imguiwindowdockstyle_193',['ImGuiWindowDockStyle',['../d8/d66/structImGuiWindowDockStyle.html',1,'']]],
  ['imguiwindowsettings_194',['ImGuiWindowSettings',['../d8/d81/structImGuiWindowSettings.html',1,'']]],
  ['imguiwindowstackdata_195',['ImGuiWindowStackData',['../db/de1/structImGuiWindowStackData.html',1,'']]],
  ['imguiwindowtempdata_196',['ImGuiWindowTempData',['../dd/db7/structImGuiWindowTempData.html',1,'']]],
  ['imnewwrapper_197',['ImNewWrapper',['../d8/dde/structImNewWrapper.html',1,'']]],
  ['impool_198',['ImPool',['../d8/d7d/structImPool.html',1,'']]],
  ['impool_3c_20imguimultiselectstate_20_3e_199',['ImPool&lt; ImGuiMultiSelectState &gt;',['../d8/d7d/structImPool.html',1,'']]],
  ['impool_3c_20imguitabbar_20_3e_200',['ImPool&lt; ImGuiTabBar &gt;',['../d8/d7d/structImPool.html',1,'']]],
  ['impool_3c_20imguitable_20_3e_201',['ImPool&lt; ImGuiTable &gt;',['../d8/d7d/structImPool.html',1,'']]],
  ['imrect_202',['ImRect',['../de/d50/structImRect.html',1,'']]],
  ['imspan_203',['ImSpan',['../da/df1/structImSpan.html',1,'']]],
  ['imspan_3c_20imguitablecelldata_20_3e_204',['ImSpan&lt; ImGuiTableCellData &gt;',['../da/df1/structImSpan.html',1,'']]],
  ['imspan_3c_20imguitablecolumn_20_3e_205',['ImSpan&lt; ImGuiTableColumn &gt;',['../da/df1/structImSpan.html',1,'']]],
  ['imspan_3c_20imguitablecolumnidx_20_3e_206',['ImSpan&lt; ImGuiTableColumnIdx &gt;',['../da/df1/structImSpan.html',1,'']]],
  ['imspanallocator_207',['ImSpanAllocator',['../da/dbe/structImSpanAllocator.html',1,'']]],
  ['imtriangulator_208',['ImTriangulator',['../dd/dca/structImTriangulator.html',1,'']]],
  ['imtriangulatornode_209',['ImTriangulatorNode',['../d0/d62/structImTriangulatorNode.html',1,'']]],
  ['imtriangulatornodespan_210',['ImTriangulatorNodeSpan',['../dc/d57/structImTriangulatorNodeSpan.html',1,'']]],
  ['imvec1_211',['ImVec1',['../d7/d7a/structImVec1.html',1,'']]],
  ['imvec2_212',['ImVec2',['../d3/dc2/structImVec2.html',1,'']]],
  ['imvec2ih_213',['ImVec2ih',['../db/dd5/structImVec2ih.html',1,'']]],
  ['imvec4_214',['ImVec4',['../dc/dee/structImVec4.html',1,'']]],
  ['imvector_215',['ImVector',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20char_20_2a_20_3e_216',['ImVector&lt; char * &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20char_20_3e_217',['ImVector&lt; char &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20const_20char_20_2a_20_3e_218',['ImVector&lt; const char * &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20dxgi_5fswap_5fchain_5fdesc_20_3e_219',['ImVector&lt; DXGI_SWAP_CHAIN_DESC &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20exampleasset_20_3e_220',['ImVector&lt; ExampleAsset &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20exampletreenode_20_2a_20_3e_221',['ImVector&lt; ExampleTreeNode * &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20float_20_3e_222',['ImVector&lt; float &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imdrawchannel_20_3e_223',['ImVector&lt; ImDrawChannel &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imdrawcmd_20_3e_224',['ImVector&lt; ImDrawCmd &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imdrawidx_20_3e_225',['ImVector&lt; ImDrawIdx &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imdrawlist_20_2a_20_3e_226',['ImVector&lt; ImDrawList * &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imdrawvert_20_3e_227',['ImVector&lt; ImDrawVert &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imdrawvertallegro_20_3e_228',['ImVector&lt; ImDrawVertAllegro &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imfont_20_2a_20_3e_229',['ImVector&lt; ImFont * &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imfontatlascustomrect_20_3e_230',['ImVector&lt; ImFontAtlasCustomRect &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imfontbuildsrcglyphft_20_3e_231',['ImVector&lt; ImFontBuildSrcGlyphFT &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imfontconfig_20_3e_232',['ImVector&lt; ImFontConfig &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imfontglyph_20_3e_233',['ImVector&lt; ImFontGlyph &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imgui_5fimplvulkan_5fframerenderbuffers_20_3e_234',['ImVector&lt; ImGui_ImplVulkan_FrameRenderBuffers &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imgui_5fimplvulkanh_5fframe_20_3e_235',['ImVector&lt; ImGui_ImplVulkanH_Frame &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imgui_5fimplvulkanh_5fframesemaphores_20_3e_236',['ImVector&lt; ImGui_ImplVulkanH_FrameSemaphores &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguicolormod_20_3e_237',['ImVector&lt; ImGuiColorMod &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguicontexthook_20_3e_238',['ImVector&lt; ImGuiContextHook &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguidocknodesettings_20_3e_239',['ImVector&lt; ImGuiDockNodeSettings &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguidockrequest_20_3e_240',['ImVector&lt; ImGuiDockRequest &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguifocusscopedata_20_3e_241',['ImVector&lt; ImGuiFocusScopeData &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguigroupdata_20_3e_242',['ImVector&lt; ImGuiGroupData &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguiid_20_3e_243',['ImVector&lt; ImGuiID &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguiinputevent_20_3e_244',['ImVector&lt; ImGuiInputEvent &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguiitemflags_20_3e_245',['ImVector&lt; ImGuiItemFlags &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguikeyroutingdata_20_3e_246',['ImVector&lt; ImGuiKeyRoutingData &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguilistclipperdata_20_3e_247',['ImVector&lt; ImGuiListClipperData &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguilistclipperrange_20_3e_248',['ImVector&lt; ImGuiListClipperRange &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguimultiselectstate_20_3e_249',['ImVector&lt; ImGuiMultiSelectState &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguimultiselecttempdata_20_3e_250',['ImVector&lt; ImGuiMultiSelectTempData &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguioldcolumndata_20_3e_251',['ImVector&lt; ImGuiOldColumnData &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguioldcolumns_20_3e_252',['ImVector&lt; ImGuiOldColumns &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguiplatformmonitor_20_3e_253',['ImVector&lt; ImGuiPlatformMonitor &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguipopupdata_20_3e_254',['ImVector&lt; ImGuiPopupData &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguiptrorindex_20_3e_255',['ImVector&lt; ImGuiPtrOrIndex &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguiselectionrequest_20_3e_256',['ImVector&lt; ImGuiSelectionRequest &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguisettingshandler_20_3e_257',['ImVector&lt; ImGuiSettingsHandler &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguishrinkwidthitem_20_3e_258',['ImVector&lt; ImGuiShrinkWidthItem &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguistacklevelinfo_20_3e_259',['ImVector&lt; ImGuiStackLevelInfo &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguistoragepair_20_3e_260',['ImVector&lt; ImGuiStoragePair &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguistylemod_20_3e_261',['ImVector&lt; ImGuiStyleMod &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguitabbar_20_3e_262',['ImVector&lt; ImGuiTabBar &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguitabitem_20_3e_263',['ImVector&lt; ImGuiTabItem &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguitable_20_3e_264',['ImVector&lt; ImGuiTable &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguitablecolumnsortspecs_20_3e_265',['ImVector&lt; ImGuiTableColumnSortSpecs &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguitableheaderdata_20_3e_266',['ImVector&lt; ImGuiTableHeaderData &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguitableinstancedata_20_3e_267',['ImVector&lt; ImGuiTableInstanceData &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguitabletempdata_20_3e_268',['ImVector&lt; ImGuiTableTempData &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguitextfilter_3a_3aimguitextrange_20_3e_269',['ImVector&lt; ImGuiTextFilter::ImGuiTextRange &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguitreenodestackdata_20_3e_270',['ImVector&lt; ImGuiTreeNodeStackData &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguiviewport_20_2a_20_3e_271',['ImVector&lt; ImGuiViewport * &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguiviewportp_20_2a_20_3e_272',['ImVector&lt; ImGuiViewportP * &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguiwindow_20_2a_20_3e_273',['ImVector&lt; ImGuiWindow * &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imguiwindowstackdata_20_3e_274',['ImVector&lt; ImGuiWindowStackData &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imtextureid_20_3e_275',['ImVector&lt; ImTextureID &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imu16_20_3e_276',['ImVector&lt; ImU16 &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imu32_20_3e_277',['ImVector&lt; ImU32 &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imu8_20_3e_278',['ImVector&lt; ImU8 &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imvec2_20_3e_279',['ImVector&lt; ImVec2 &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imvec4_20_3e_280',['ImVector&lt; ImVec4 &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20imwchar_20_3e_281',['ImVector&lt; ImWchar &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20int_20_3e_282',['ImVector&lt; int &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20mydocument_20_2a_20_3e_283',['ImVector&lt; MyDocument * &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20mydocument_20_3e_284',['ImVector&lt; MyDocument &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20sdl_5ffcolor_20_3e_285',['ImVector&lt; SDL_FColor &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20sdl_5fgamecontroller_20_2a_20_3e_286',['ImVector&lt; SDL_GameController * &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20sdl_5fgamepad_20_2a_20_3e_287',['ImVector&lt; SDL_Gamepad * &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['imvector_3c_20unsigned_20char_20_3e_288',['ImVector&lt; unsigned char &gt;',['../d6/d97/structImVector.html',1,'']]],
  ['inombre_289',['INombre',['../dc/d68/classCE_1_1INombre.html',1,'CE']]],
  ['inputbuffer_290',['InputBuffer',['../dc/dfa/classCE_1_1InputBuffer.html',1,'CE']]],
  ['inputtextcallback_5fuserdata_291',['InputTextCallback_UserData',['../d8/dd1/structInputTextCallback__UserData.html',1,'']]],
  ['ipaths_292',['IPaths',['../da/dd7/classCE_1_1IPaths.html',1,'CE']]],
  ['irayo_293',['IRayo',['../df/db6/classIVJ_1_1IRayo.html',1,'IVJ']]],
  ['irespawn_294',['IRespawn',['../d8/daa/classCE_1_1IRespawn.html',1,'CE']]],
  ['ishader_295',['IShader',['../df/d69/classCE_1_1IShader.html',1,'CE']]],
  ['isprite_296',['ISprite',['../d6/da3/classCE_1_1ISprite.html',1,'CE']]],
  ['istats_297',['IStats',['../dd/ddd/classCE_1_1IStats.html',1,'CE']]],
  ['itexto_298',['ITexto',['../d7/d95/classCE_1_1ITexto.html',1,'CE']]],
  ['itimer_299',['ITimer',['../d4/d0b/classCE_1_1ITimer.html',1,'CE']]],
  ['itransform_300',['ITransform',['../d1/d52/classCE_1_1ITransform.html',1,'CE']]]
];
